import assert from "node:assert/strict";
import test from "node:test";
import { getAvailableModes, getLanguageConfig, getWordDisplayForms } from "./languages";
import { comparePinyin, normalizePinyinForSearch } from "./pinyin";
import { gradeLanguageAnswer } from "./languageAnswer";

test("language registry preserves English and configures Mandarin",()=>{assert.equal(getLanguageConfig("en").ttsLanguage,"en-US");assert.equal(getLanguageConfig("zh-CN").recognitionLanguage,"zh-CN");assert.equal(getAvailableModes({type:"language_vocab",languageCode:"zh-CN"}).includes("sentence"),false);assert.equal(getAvailableModes({type:"ielts_vocab",languageCode:"en"}).includes("sentence"),true);});
test("Chinese display respects script settings",()=>{const word={term:"学习",alternateTerm:"學習"};assert.deepEqual(getWordDisplayForms(word,{languageCode:"zh-CN",languageSettings:'{"scriptVariant":"simplified"}'}),{primary:"学习",secondary:"學習"});assert.deepEqual(getWordDisplayForms(word,{languageCode:"zh-CN",languageSettings:'{"scriptVariant":"traditional"}'}),{primary:"學習",secondary:"学习"});});
test("strict Pinyin accepts marks and numbers but reports missing tones",()=>{assert.equal(comparePinyin("xuéxí","xuéxí","strict").correct,true);assert.equal(comparePinyin("xue2xi2","xuéxí","strict").correct,true);const miss=comparePinyin("xuexi","xuéxí","strict");assert.equal(miss.correct,false);assert.equal(miss.nearMiss,true);assert.equal(comparePinyin("xuexi","xuéxí","relaxed").correct,true);});
test("Pinyin normalizes ü, apostrophes, neutral tone and search",()=>{assert.equal(comparePinyin("lv4","lǜ","strict").correct,true);assert.equal(comparePinyin("lu:4","lǜ","strict").correct,true);assert.equal(comparePinyin("xi1'an1","Xī'ān","strict").correct,true);assert.equal(comparePinyin("ma5","ma","strict").correct,true);assert.equal(normalizePinyinForSearch("xuéxí"),"xuexi");});
test("Hanzi grading is exact and accepts configured both scripts",()=>{const set={languageCode:"zh-CN",languageSettings:'{"scriptVariant":"both","pinyinTonePolicy":"strict"}'};const word={term:"学习",alternateTerm:"學習",pronunciation:"xuéxí"};assert.equal(gradeLanguageAnswer({set,word,userAnswer:"学习"}).correct,true);assert.equal(gradeLanguageAnswer({set,word,userAnswer:"學習"}).correct,true);assert.equal(gradeLanguageAnswer({set,word,userAnswer:"学生"}).correct,false);assert.equal(gradeLanguageAnswer({set,word,target:"pronunciation",userAnswer:"xue2xi2"}).correct,true);});
