import { gradeFillAnswer, normalizeFillAnswer } from "@/lib/fillAnswer";
import { getChineseSettings } from "@/lib/languageSettings";
import { normalizeLanguageCode, type FillTarget } from "@/lib/languages";
import { comparePinyin } from "@/lib/pinyin";
export type LanguageAnswerGrade={correct:boolean;nearMiss:boolean;reason?:"missing_or_wrong_tone";acceptedAnswers:string[]};
function normalizeHanzi(value:string|null|undefined){return(value||"").normalize("NFC").trim().replace(/\s+/g," ").replace(/[。！？!?]+$/u,"");}
export function getTargetAcceptedAnswers(input:{set:{languageCode?:string|null;languageSettings?:unknown};word:{term?:string|null;alternateTerm?:string|null;pronunciation?:string|null};target?:FillTarget}){const target=input.target||"term";if(target==="pronunciation")return input.word.pronunciation?[input.word.pronunciation]:[];if(normalizeLanguageCode(input.set.languageCode)!=="zh-CN")return input.word.term?[input.word.term]:[];const settings=getChineseSettings(input.set);if(settings.scriptVariant==="traditional")return[input.word.alternateTerm||input.word.term||""].filter(Boolean);if(settings.scriptVariant==="both")return[...new Set([input.word.term,input.word.alternateTerm].filter((v):v is string=>Boolean(v)))];return[input.word.term||input.word.alternateTerm||""].filter(Boolean);}
export function gradeLanguageAnswer(input:{set:{languageCode?:string|null;languageSettings?:unknown};word:{term?:string|null;alternateTerm?:string|null;pronunciation?:string|null};target?:FillTarget;userAnswer:string}):LanguageAnswerGrade{const language=normalizeLanguageCode(input.set.languageCode),target=input.target||"term",acceptedAnswers=getTargetAcceptedAnswers(input);if(language==="en"&&target==="term")return gradeFillAnswer(input.userAnswer,input.word.term);if(language==="zh-CN"&&target==="pronunciation"){const settings=getChineseSettings(input.set),grades=acceptedAnswers.map(answer=>comparePinyin(input.userAnswer,answer,settings.pinyinTonePolicy));return{correct:grades.some(g=>g.correct),nearMiss:grades.some(g=>g.nearMiss),reason:grades.find(g=>g.reason)?.reason,acceptedAnswers};}const normalized=normalizeHanzi(input.userAnswer);return{correct:Boolean(normalized)&&acceptedAnswers.some(answer=>normalizeHanzi(answer)===normalized),nearMiss:false,acceptedAnswers};}
export function normalizeLanguageSearch(value:string|null|undefined){return normalizeFillAnswer(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d");}
