import test from "node:test";
import assert from "node:assert/strict";
import { normalizeQuestionImportText, parseQuestionImport, revalidateParsedQuestion } from "./questionImportParser";

const mc = (markers = ["A.", "B.", "C.", "D."]) => `Câu 1. Tính toàn vẹn đảm bảo điều gì?\n${markers[0]} Chỉ người có quyền được sửa\n${markers[1]} Mọi người được sửa\n${markers[2]} Luôn trực tuyến\n${markers[3]} Chỉ sao lưu\nĐáp án: A`;
test("parses standard A/B/C/D", () => { const [q] = parseQuestionImport(mc()); assert.equal(q.type, "multiple_choice"); assert.equal(q.options.length, 4); assert.equal(q.options[0].isCorrect, true); });
test("parses A) B) C) D)", () => assert.equal(parseQuestionImport(mc(["A)", "B)", "C)", "D)"]))[0].options.length, 4));
test("parses lowercase options", () => assert.equal(parseQuestionImport(mc(["a.", "b.", "c.", "d."]))[0].options[0].id, "A"));
test("parses numbered options", () => { const [q] = parseQuestionImport("1. Chọn màu?\n1) Đỏ\n2) Xanh\n3) Vàng\nĐáp án: 2"); assert.equal(q.options.length, 3); assert.equal(q.options[1].isCorrect, true); });
test("detects Vietnamese Câu 1", () => assert.equal(parseQuestionImport(mc())[0].sourceNumber, "1"));
test("detects English Question 1", () => assert.equal(parseQuestionImport(mc().replace("Câu 1.", "Question 1:"))[0].sourceNumber, "1"));
test("detects Vietnamese answer", () => assert.equal(parseQuestionImport(mc())[0].options[0].isCorrect, true));
test("detects English answer", () => assert.equal(parseQuestionImport(mc().replace("Đáp án: A", "Answer: B"))[0].options[1].isCorrect, true));
test("applies final answer list", () => { const items = parseQuestionImport("1. Một cộng một?\nA. 1\nB. 2\n\n2. Hai cộng hai?\nA. 3\nB. 4\n\nĐáp án\n1-B\n2-B"); assert.equal(items.length, 2); assert.equal(items[1].options[1].isCorrect, true); });
test("missing answer is review without guessing", () => { const [q] = parseQuestionImport(mc().replace("\nĐáp án: A", "")); assert.ok(q.issues.includes("MISSING_CORRECT_ANSWER")); assert.equal(q.options.some((option) => option.isCorrect), false); });
test("supports multiple correct answers", () => { const [q] = parseQuestionImport(mc().replace("Đáp án: A", "Correct: A,C")); assert.deepEqual(q.options.filter((o) => o.isCorrect).map((o) => o.id), ["A", "C"]); });
test("recovers PDF wrapped lines", () => { const [q] = parseQuestionImport("33. Tính toàn vẹn\n(Integrity) đảm bảo\nđiều gì?\nA. Thông tin chỉ\ncó thể sửa bởi\nngười có quyền\nB. Mọi người đều\ncó thể sửa\nĐáp án: A"); assert.match(q.question, /Integrity.*điều gì/u); assert.match(q.options[0].text, /sửa bởi người/u); });
test("normalizes extra blank lines", () => assert.equal(parseQuestionImport(mc().replace(/\n/g, "\n\n\n"))[0].options.length, 4));
test("works without blank lines", () => assert.equal(parseQuestionImport(mc())[0].options.length, 4));
test("parses mixed MCQ and essay", () => { const items = parseQuestionImport(`${mc()}\n2. Trình bày CIA.\nTrả lời: Bí mật, toàn vẹn, sẵn dùng.`); assert.deepEqual(items.map((q) => q.type), ["multiple_choice", "essay"]); });
test("detects duplicate questions", () => { const items = parseQuestionImport(`${mc()}\n2. Tính toàn vẹn đảm bảo điều gì?\nA. X\nB. Y\nĐáp án: A`); assert.ok(items[1].issues.includes("POSSIBLE_DUPLICATE")); });
test("detects empty option after edit", () => { const [q] = parseQuestionImport(mc()); const changed = revalidateParsedQuestion({ ...q, options: q.options.map((o, i) => i ? o : { ...o, text: "" }) }); assert.ok(changed.issues.includes("EMPTY_OPTION")); });
test("detects conflicting answers", () => { const [q] = parseQuestionImport(mc().replace("A. Chỉ", "*A. Chỉ").replace("Đáp án: A", "Đáp án: B")); assert.ok(q.issues.includes("CONFLICTING_ANSWERS")); });
test("parses two-option True/False", () => { const [q] = parseQuestionImport("1. Trái đất tròn?\nA. Đúng\nB. Sai\nĐáp án: A"); assert.equal(q.type, "true_false"); });
test("supports 5+ options", () => { const [q] = parseQuestionImport("1. Chọn?\nA. a\nB. b\nC. c\nD. d\nE. e\nF. f\nAnswer: F"); assert.equal(q.options.length, 6); assert.equal(q.options[5].isCorrect, true); });
test("malformed question becomes error or review", () => { const [q] = parseQuestionImport("1. ?\nA. only"); assert.notEqual(q.status, "ready"); });
test("handles large input", () => { const raw = Array.from({ length: 1500 }, (_, i) => `${i + 1}. Câu hỏi số ${i + 1}?\nA. Đúng\nB. Sai\nĐáp án: A`).join("\n"); const started = Date.now(); const items = parseQuestionImport(raw); assert.equal(items.length, 1500); assert.ok(Date.now() - started < 4000); });
test("normalizes Unicode, whitespace and line endings", () => assert.equal(normalizeQuestionImportText("  Câu\u00a01\r\n\tA.  Test  "), "Câu 1\nA. Test"));
test("parses IELTS Speaking parts", () => { const items = parseQuestionImport("PART 1\nTopic: Hometown\n1. Where is your hometown?\n2. What do you like about it?\nPART 2\nDescribe your hometown.\nYou should say:\n* where it is\n* why you like it"); assert.equal(items[0].type, "speaking"); assert.equal(items.at(-1)?.speakingPart, "part_2"); });
test("supports standalone question numbers", () => { const [q] = parseQuestionImport("1.\nNội dung câu hỏi?\nA. Một\nB. Hai\nĐáp án:\nB"); assert.equal(q.sourceNumber, "1"); assert.equal(q.options[1].isCorrect, true); });
test("supports Q1 marker", () => assert.equal(parseQuestionImport("Q1: Which one?\nA - One\nB - Two\nCorrect option = 1")[0].options[0].isCorrect, true));
test("custom profile applies safe patterns", () => { const [q] = parseQuestionImport("Question No: Custom?\nChoice 1: First\nChoice 2: Second\nSolution: B", { profile: { name: "Custom", questionPattern: "^Question No:\\s*(.*)$", optionPattern: "^Choice\\s*(\\d+)[:.-]\\s*(.*)$", answerPattern: "^Solution:\\s*(.*)$", defaultType: "multiple_choice" } }); assert.equal(q.type, "multiple_choice"); });
