export const IRREGULAR_VERBS_SEED = [
{v1:"arise",v2:"arose",v3:"arisen",m:"nảy sinh"},{v1:"awake",v2:"awoke",v3:"awoken",m:"thức tỉnh"},
{v1:"be",v2:"was/were",v3:"been",m:"là"},{v1:"bear",v2:"bore",v3:"borne/born",m:"chịu"},
{v1:"beat",v2:"beat",v3:"beaten/beat",m:"đánh đập"},{v1:"become",v2:"became",v3:"become",m:"trở thành"},
{v1:"begin",v2:"began",v3:"begun",m:"bắt đầu"},{v1:"bend",v2:"bent",v3:"bent",m:"bẻ cong"},
{v1:"bet",v2:"bet",v3:"bet",m:"cá cược"},{v1:"bid",v2:"bid",v3:"bid",m:"đấu thầu, đấu giá"},
{v1:"bind",v2:"bound",v3:"bound",m:"trói buộc"},{v1:"bite",v2:"bit",v3:"bitten",m:"cắn"},
{v1:"bleed",v2:"bled",v3:"bled",m:"chảy máu"},{v1:"blow",v2:"blew",v3:"blown",m:"thổi"},
{v1:"break",v2:"broke",v3:"broken",m:"phá vỡ"},{v1:"breed",v2:"bred",v3:"bred",m:"sinh ra"},
{v1:"bring",v2:"brought",v3:"brought",m:"cung cấp, mang tới"},{v1:"broadcast",v2:"broadcast",v3:"broadcast",m:"truyền phát"},
{v1:"build",v2:"built",v3:"built",m:"xây dựng"},{v1:"burn",v2:"burned/burnt",v3:"burned/burnt",m:"đốt cháy"},
{v1:"burst",v2:"burst",v3:"burst",m:"nổ"},{v1:"buy",v2:"bought",v3:"bought",m:"mua"},
{v1:"cast",v2:"cast",v3:"cast",m:"tuyển (vai diễn)"},{v1:"catch",v2:"caught",v3:"caught",m:"bắt, chụp lấy"},
{v1:"choose",v2:"chose",v3:"chosen",m:"chọn"},{v1:"cling",v2:"clung",v3:"clung",m:"bám vào"},
{v1:"come",v2:"came",v3:"come",m:"đến"},{v1:"cost",v2:"cost",v3:"cost",m:"mất (bao nhiêu tiền)"},
{v1:"creep",v2:"crept",v3:"crept",m:"leo, di chuyển lén lút"},{v1:"cut",v2:"cut",v3:"cut",m:"cắt"},
{v1:"deal",v2:"dealt",v3:"dealt",m:"thỏa thuận, xử lý"},{v1:"dig",v2:"dug",v3:"dug",m:"đào"},
{v1:"do",v2:"did",v3:"done",m:"làm"},{v1:"draw",v2:"drew",v3:"drawn",m:"vẽ tranh"},
{v1:"dream",v2:"dreamed/dreamt",v3:"dreamed/dreamt",m:"mơ ước"},{v1:"drink",v2:"drank",v3:"drunk",m:"uống"},
{v1:"drive",v2:"drove",v3:"driven",m:"lái xe"},{v1:"eat",v2:"ate",v3:"eaten",m:"ăn"},
{v1:"fall",v2:"fell",v3:"fallen",m:"rơi, ngã"},{v1:"feed",v2:"fed",v3:"fed",m:"cho ăn"},
{v1:"feel",v2:"felt",v3:"felt",m:"cảm thấy"},{v1:"fight",v2:"fought",v3:"fought",m:"đánh nhau"},
{v1:"find",v2:"found",v3:"found",m:"tìm thấy"},{v1:"fit",v2:"fit/fitted",v3:"fit/fitted",m:"phù hợp, vừa vặn"},
{v1:"flee",v2:"fled",v3:"fled",m:"chạy trốn"},{v1:"fling",v2:"flung",v3:"flung",m:"quăng ra"},
{v1:"fly",v2:"flew",v3:"flown",m:"bay"},{v1:"forbid",v2:"forbade",v3:"forbidden",m:"ngăn cấm"},
{v1:"forecast",v2:"forecast",v3:"forecast",m:"dự báo"},{v1:"forget",v2:"forgot",v3:"forgotten",m:"quên đi"},
{v1:"forgive",v2:"forgave",v3:"forgiven",m:"tha lỗi"},{v1:"forsake",v2:"forsook",v3:"forsaken",m:"từ bỏ"},
{v1:"freeze",v2:"froze",v3:"frozen",m:"đông cứng"},{v1:"get",v2:"got",v3:"gotten/got",m:"lấy"},
{v1:"give",v2:"gave",v3:"given",m:"cho"},{v1:"go",v2:"went",v3:"gone",m:"đi"},
{v1:"grind",v2:"ground",v3:"ground",m:"xay, nghiền"},{v1:"grow",v2:"grew",v3:"grown",m:"lớn lên, phát triển"},
{v1:"hang",v2:"hung",v3:"hung",m:"treo"},{v1:"have",v2:"had",v3:"had",m:"có"},
{v1:"hear",v2:"heard",v3:"heard",m:"nghe"},{v1:"hide",v2:"hid",v3:"hidden",m:"ẩn giấu"},
{v1:"hit",v2:"hit",v3:"hit",m:"đánh"},{v1:"hold",v2:"held",v3:"held",m:"nắm giữ, tổ chức"},
{v1:"hurt",v2:"hurt",v3:"hurt",m:"làm tổn thương"},{v1:"keep",v2:"kept",v3:"kept",m:"giữ cho"},
{v1:"kneel",v2:"kneeled/knelt",v3:"kneeled/knelt",m:"quỳ xuống"},{v1:"know",v2:"knew",v3:"known",m:"biết"},
{v1:"lay",v2:"laid",v3:"laid",m:"đặt nằm"},{v1:"lead",v2:"led",v3:"led",m:"dẫn (đến), chỉ đạo"},
{v1:"lean",v2:"leaned/leant",v3:"leaned/leant",m:"nghiêng (về)"},{v1:"leap",v2:"leaped/leapt",v3:"leaped/leapt",m:"nhảy vọt"},
{v1:"learn",v2:"learned/learnt",v3:"learned/learnt",m:"học"},{v1:"leave",v2:"left",v3:"left",m:"rời bỏ"},
{v1:"lend",v2:"lent",v3:"lent",m:"cho mượn"},{v1:"let",v2:"let",v3:"let",m:"cho phép"},
{v1:"lie",v2:"lay",v3:"lain",m:"nằm xuống"},{v1:"light",v2:"lighted/lit",v3:"lighted/lit",m:"thắp sáng"},
{v1:"lose",v2:"lost",v3:"lost",m:"mất, thua"},{v1:"make",v2:"made",v3:"made",m:"làm, tạo ra"},
{v1:"mean",v2:"meant",v3:"meant",m:"nghĩa là, có ý"},{v1:"meet",v2:"met",v3:"met",m:"gặp"},
{v1:"mislay",v2:"mislaid",v3:"mislaid",m:"làm mất"},{v1:"mistake",v2:"mistook",v3:"mistaken",m:"sai lầm, ngộ nhận"},
{v1:"pay",v2:"paid",v3:"paid",m:"trả tiền"},{v1:"prove",v2:"proved",v3:"proven/proved",m:"chứng tỏ"},
{v1:"put",v2:"put",v3:"put",m:"đặt"},{v1:"quit",v2:"quit/quitted",v3:"quit/quitted",m:"từ bỏ, thôi việc"},
{v1:"read",v2:"read",v3:"read",m:"đọc"},{v1:"rid",v2:"rid",v3:"rid",m:"loại bỏ"},
{v1:"ride",v2:"rode",v3:"ridden",m:"cưỡi, đi xe"},{v1:"ring",v2:"rang",v3:"rung",m:"reo chuông"},
{v1:"rise",v2:"rose",v3:"risen",m:"nổi lên, tăng lên"},{v1:"run",v2:"ran",v3:"run",m:"chạy, vận hành"},
{v1:"say",v2:"said",v3:"said",m:"nói"},{v1:"see",v2:"saw",v3:"seen",m:"nhìn thấy"},
{v1:"seek",v2:"sought",v3:"sought",m:"tìm kiếm"},{v1:"sell",v2:"sold",v3:"sold",m:"bán"},
{v1:"send",v2:"sent",v3:"sent",m:"gửi"},{v1:"set",v2:"set",v3:"set",m:"đặt, thiết lập"},
{v1:"shake",v2:"shook",v3:"shaken",m:"lắc, rung chuyển"},{v1:"shed",v2:"shed",v3:"shed",m:"rơi, rụng, loại trừ"},
{v1:"shine",v2:"shone/shined",v3:"shone/shined",m:"chiếu sáng"},{v1:"shoot",v2:"shot",v3:"shot",m:"bắn"},
{v1:"show",v2:"showed",v3:"shown/showed",m:"thể hiện"},{v1:"shrink",v2:"shrank/shrunk",v3:"shrunk",m:"co lại"},
{v1:"shut",v2:"shut",v3:"shut",m:"đóng"},{v1:"sing",v2:"sang",v3:"sung",m:"hát"},
{v1:"sink",v2:"sank",v3:"sunk",m:"chìm, trầm (xuống)"},{v1:"sit",v2:"sat",v3:"sat",m:"ngồi"},
{v1:"sleep",v2:"slept",v3:"slept",m:"ngủ"},{v1:"slide",v2:"slid",v3:"slid",m:"trượt"},
{v1:"slit",v2:"slit",v3:"slit",m:"rạch"},{v1:"smell",v2:"smelled/smelt",v3:"smelled/smelt",m:"ngửi, đánh hơi"},
{v1:"sneak",v2:"sneaked/snuck",v3:"sneaked/snuck",m:"lẻn"},{v1:"speak",v2:"spoke",v3:"spoken",m:"nói"},
{v1:"speed",v2:"sped/speeded",v3:"sped/speeded",m:"di chuyển nhanh chóng"},{v1:"spell",v2:"spelled/spelt",v3:"spelled/spelt",m:"đánh vần"},
{v1:"spend",v2:"spent",v3:"spent",m:"tiêu (tiền), dùng"},{v1:"spill",v2:"spilled/spilt",v3:"spilled/spilt",m:"đổ tràn"},
{v1:"spin",v2:"spun",v3:"spun",m:"quay, xoay"},{v1:"spit",v2:"spit/spat",v3:"spit/spat",m:"khạc nhổ"},
{v1:"split",v2:"split",v3:"split",m:"tách ra"},{v1:"spoil",v2:"spoiled/spoilt",v3:"spoiled/spoilt",m:"làm hư"},
{v1:"spread",v2:"spread",v3:"spread",m:"trải ra, lan truyền"},{v1:"spring",v2:"sprang/sprung",v3:"sprung",m:"nảy lên, đến từ"},
{v1:"stand",v2:"stood",v3:"stood",m:"đứng"},{v1:"steal",v2:"stole",v3:"stolen",m:"ăn cắp"},
{v1:"stick",v2:"stuck",v3:"stuck",m:"dính, đâm"},{v1:"sting",v2:"stung",v3:"stung",m:"chích, đốt, đâm"},
{v1:"stink",v2:"stank/stunk",v3:"stunk",m:"có mùi hôi"},{v1:"strike",v2:"struck",v3:"struck/stricken",m:"đánh đập, ập đến"},
{v1:"strive",v2:"strove/strived",v3:"striven/strived",m:"phấn đấu"},{v1:"string",v2:"strung",v3:"strung",m:"xâu chuỗi"},
{v1:"swear",v2:"swore",v3:"sworn",m:"thề"},{v1:"sweep",v2:"swept",v3:"swept",m:"quét"},
{v1:"swell",v2:"swelled",v3:"swelled/swollen",m:"sưng lên"},{v1:"swim",v2:"swam",v3:"swum",m:"bơi"},
{v1:"swing",v2:"swung",v3:"swung",m:"lung lay, đu đưa"},{v1:"take",v2:"took",v3:"taken",m:"cầm lấy"},
{v1:"teach",v2:"taught",v3:"taught",m:"dạy"},{v1:"tear",v2:"tore",v3:"torn",m:"xé"},
{v1:"tell",v2:"told",v3:"told",m:"kể"},{v1:"think",v2:"thought",v3:"thought",m:"nghĩ"},
{v1:"throw",v2:"threw",v3:"thrown",m:"ném"},{v1:"thrust",v2:"thrust",v3:"thrust",m:"đẩy"},
{v1:"understand",v2:"understood",v3:"understood",m:"hiểu"},{v1:"undertake",v2:"undertook",v3:"undertaken",m:"đảm nhận"},
{v1:"upset",v2:"upset",v3:"upset",m:"gây khó chịu"},{v1:"wake",v2:"woke/waked",v3:"woken",m:"đánh thức, thức dậy"},
{v1:"wear",v2:"wore",v3:"worn",m:"mặc"},{v1:"weave",v2:"wove",v3:"woven",m:"dệt"},
{v1:"weep",v2:"wept",v3:"wept",m:"khóc"},{v1:"win",v2:"won",v3:"won",m:"thắng lợi"},
{v1:"wind",v2:"wound",v3:"wound",m:"xoay, vặn"},{v1:"withdraw",v2:"withdrew",v3:"withdrawn",m:"rút"},
{v1:"write",v2:"wrote",v3:"written",m:"viết"}
];

export const IELTS_VOCAB_SEED = [
{term:"abandon",meaning:"từ bỏ, bỏ rơi",example:"They had to abandon the project.",type:"verb"},
{term:"accumulate",meaning:"tích lũy, tích tụ",example:"Debt accumulated over the years.",type:"verb"},
{term:"adequate",meaning:"đủ, thỏa đáng",example:"The funding was not adequate.",type:"adj"},
{term:"controversial",meaning:"gây tranh cãi",example:"It was a controversial decision.",type:"adj"},
{term:"diminish",meaning:"giảm bớt, suy giảm",example:"Their influence began to diminish.",type:"verb"},
{term:"enhance",meaning:"nâng cao, cải thiện",example:"This will enhance the quality of life.",type:"verb"},
{term:"feasible",meaning:"khả thi",example:"The plan seems feasible.",type:"adj"},
{term:"substantial",meaning:"đáng kể, to lớn",example:"A substantial amount of money.",type:"adj"},
{term:"phenomenon",meaning:"hiện tượng",example:"An interesting social phenomenon.",type:"noun"},
{term:"inevitable",meaning:"tất yếu, không thể tránh khỏi",example:"Change is inevitable.",type:"adj"}
];
