import Link from "next/link";

const stats = [
  { label: "Học viên đang hoạt động", value: "1,284", delta: "+12,8%", icon: "◎", color: "bg-[#EFECFF] text-[#6550DB]" },
  { label: "Điểm trung bình", value: "6.8", delta: "+0.4", icon: "↗", color: "bg-[#E7F7F2] text-[#398B73]" },
  { label: "Hoàn thành khóa học", value: "72%", delta: "+8,2%", icon: "✓", color: "bg-[#FFF0E8] text-[#D87855]" },
  { label: "Nội dung", value: "342", delta: "+24 tháng này", icon: "▤", color: "bg-[#FFF8DF] text-[#B28A20]" },
];

export default function AdminDashboardPage() {
  return <div className="lexora-page-enter space-y-6">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold text-gold">Khu quản trị / Tổng quan</p><h1 className="text-[clamp(1.8rem,4vw,2.5rem)] font-extrabold tracking-[-0.045em]">Điều hành học viện.</h1><p className="mt-2 text-[0.95rem] text-muted">Theo dõi học viên, khóa học và hiệu quả nội dung.</p></div><Link href="/admin/sets" className="inline-flex h-11 items-center justify-center rounded-[11px] bg-gold px-4 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-golddark">+ Tạo khóa học</Link></section>
    <section className="lexora-stagger grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <article key={stat.label} className="lexora-card p-5 transition hover:-translate-y-1"><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-[12px] text-sm font-extrabold ${stat.color}`}>{stat.icon}</span><span className="text-[0.68rem] font-bold text-[#398B73]">{stat.delta}</span></div><p className="mt-5 text-xs font-semibold text-muted">{stat.label}</p><strong className="mt-1 block text-2xl font-extrabold tracking-[-0.03em]">{stat.value}</strong></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,0.9fr)]"><article className="lexora-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-extrabold">Quick Manage</h2><p className="mt-1 text-xs text-muted">Keep your academy moving.</p></div><span className="rounded-full bg-[#F7F6FA] px-2.5 py-1 text-[0.68rem] font-bold text-muted">4 shortcuts</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[{href:"/admin/sets",title:"Vocabulary sets",detail:"128 words to review",icon:"Aa",color:"#EFECFF"},{href:"/admin/assignments",title:"Assignments",detail:"18 active this week",icon:"✓",color:"#E7F7F2"},{href:"/admin/users",title:"Learners",detail:"1,284 enrolled",icon:"◎",color:"#FFF0E8"},{href:"/admin/import",title:"Import content",detail:"Add a new resource",icon:"↑",color:"#FFF8DF"}].map((item) => <Link href={item.href} key={item.title} className="flex items-center gap-3 rounded-[13px] border border-line p-3 transition hover:-translate-y-0.5 hover:border-[#D8D2FF] hover:bg-[#FBFAFE]"><span className="flex h-10 w-10 items-center justify-center rounded-[11px] text-sm font-extrabold text-[#6550DB]" style={{backgroundColor:item.color}}>{item.icon}</span><span className="min-w-0"><b className="block text-xs">{item.title}</b><span className="mt-1 block truncate text-[0.68rem] text-muted">{item.detail}</span></span><span className="ml-auto text-muted">→</span></Link>)}</div></article>
      <article className="lexora-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-extrabold">Recent activity</h2><p className="mt-1 text-xs text-muted">What is happening today.</p></div><Link href="/admin/results" className="text-xs font-bold text-gold hover:underline">View all</Link></div><div className="mt-5 space-y-4">{[{name:"Mia Thompson",action:"completed Listening mock test",time:"8 min ago",avatar:"MT",color:"#EFECFF"},{name:"Noah Williams",action:"joined Academic Writing",time:"32 min ago",avatar:"NW",color:"#E7F7F2"},{name:"Olivia Chen",action:"mastered 18 new words",time:"1 hr ago",avatar:"OC",color:"#FFF0E8"}].map((item) => <div key={item.name} className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[0.62rem] font-extrabold text-[#6550DB]" style={{backgroundColor:item.color}}>{item.avatar}</span><div className="min-w-0 flex-1"><p className="truncate text-xs"><b>{item.name}</b> <span className="text-muted">{item.action}</span></p><span className="text-[0.68rem] text-muted">{item.time}</span></div></div>)}</div></article></section>
    <section className="lexora-card flex flex-col items-start justify-between gap-4 bg-[#302A68] p-6 text-white sm:flex-row sm:items-center"><div><span className="text-[0.68rem] font-bold uppercase tracking-[0.14em] text-[#C8C2FF]">Academy pulse</span><h2 className="mt-2 text-xl font-extrabold">Your learners are building a strong rhythm.</h2><p className="mt-1 text-sm text-[#D3D0EC]">Weekly practice time is up 18% compared with last month.</p></div><Link href="/admin/progress" className="shrink-0 rounded-[11px] bg-white px-4 py-2.5 text-sm font-bold text-[#302A68] transition hover:-translate-y-0.5">See progress →</Link></section>
  </div>;
}
