"use client";

import { useEffect, useMemo, useState } from "react";
import Modal from "@/components/Modal";
import { cx } from "@/components/ui";
import { QUESTION_SHARE_MODES, modesForSetType, type ShareTargetType } from "@/lib/shareConfig";

const modeLabels: Record<string, string> = { learn: "Học bài", fill: "Điền từ", mc: "Trắc nghiệm", match: "Ghép cặp", dictation: "Nghe & viết", pronunciation: "Luyện phát âm", sentence: "Xếp câu", timed: "Thi thử tính giờ", practice: "Luyện câu hỏi", multiple_choice: "Trắc nghiệm", speaking: "Speaking", shuffle: "Xáo trộn câu hỏi" };

export default function ShareDialog({ targetType, targetId, title, setType, onClose }: { targetType: ShareTargetType; targetId: number; title: string; setType?: string; onClose: () => void }) {
  const modes = useMemo(() => targetType === "vocab_set" ? [...modesForSetType(setType || "ielts_vocab")] : [...QUESTION_SHARE_MODES], [setType, targetType]);
  const [accessMode, setAccessMode] = useState<"restricted" | "anyone_with_link">("restricted");
  const [allowedModes, setAllowedModes] = useState<string[]>(modes);
  const [shareUrl, setShareUrl] = useState(() => { try { return localStorage.getItem(`lexora-share-url-${targetType}-${targetId}`) || ""; } catch { return ""; } });
  const [busy, setBusy] = useState(true);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  async function safeJson(response: Response): Promise<Record<string, any>> { const text = await response.text(); if (!text) return {}; try { const parsed = JSON.parse(text); return parsed && typeof parsed === "object" ? parsed : {}; } catch { return {}; } }
  useEffect(() => { let active = true; setBusy(true); setError(""); fetch(`/api/share?targetType=${targetType}&targetId=${targetId}`).then(async (response) => { const data = await safeJson(response); if (!response.ok) throw new Error(data.error || "Không thể tải cấu hình liên kết chia sẻ."); if (active && data.share) { setAccessMode(data.share.accessMode); setAllowedModes(data.share.allowedModes || modes); } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Không thể tải cấu hình liên kết chia sẻ."); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [modes, targetId, targetType]);
  async function save() { setBusy(true); setError(""); try { const response = await fetch("/api/share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ targetType, targetId, accessMode, allowedModes }) }); const data = await safeJson(response); if (!response.ok) throw new Error(data.error || "Không thể lưu liên kết chia sẻ."); if (data.share?.url) { setShareUrl(data.share.url); try { localStorage.setItem(`lexora-share-url-${targetType}-${targetId}`, data.share.url); } catch {} } if (accessMode === "restricted") { setShareUrl(""); try { localStorage.removeItem(`lexora-share-url-${targetType}-${targetId}`); } catch {} } } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể lưu liên kết chia sẻ."); } finally { setBusy(false); } }
  async function copy() { if (!shareUrl) return; await navigator.clipboard?.writeText(shareUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  return <Modal title={`Chia sẻ ${title}`} onClose={onClose}><div className="space-y-5"><fieldset><legend className="text-xs font-bold uppercase tracking-wide text-muted">Quyền truy cập chung</legend><label className="mt-3 flex cursor-pointer items-start gap-3 rounded-lg border border-line p-3"><input type="radio" name="share-access" checked={accessMode === "restricted"} onChange={() => setAccessMode("restricted")} /><span><b className="block text-sm">Bị giới hạn</b><span className="text-xs text-muted">Chỉ tài khoản được cấp quyền.</span></span></label><label className="mt-2 flex cursor-pointer items-start gap-3 rounded-lg border border-line p-3"><input type="radio" name="share-access" checked={accessMode === "anyone_with_link"} onChange={() => setAccessMode("anyone_with_link")} /><span><b className="block text-sm">Bất kỳ ai có liên kết</b><span className="text-xs text-muted">Không cần đăng nhập để học và luyện.</span></span></label></fieldset>{accessMode === "anyone_with_link" && <fieldset><legend className="text-xs font-bold uppercase tracking-wide text-muted">Cho phép học bằng</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{modes.map((mode) => <label key={mode} className="flex cursor-pointer items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm"><input type="checkbox" checked={allowedModes.includes(mode)} onChange={(event) => setAllowedModes((current) => event.target.checked ? [...new Set([...current, mode])] : current.filter((item) => item !== mode))} />{modeLabels[mode] || mode}</label>)}</div></fieldset>}{error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button type="button" className={`${cx.btn} ${cx.btnGold} w-full`} disabled={busy || (accessMode === "anyone_with_link" && allowedModes.length === 0)} onClick={() => void save()}>{busy ? "Đang lưu…" : "Lưu quyền chia sẻ"}</button>{shareUrl && accessMode === "anyone_with_link" && <div className="rounded-lg border border-line bg-[#FAF9FD] p-3"><input readOnly value={shareUrl} className={`${cx.input} !mb-2 text-xs`} aria-label="Liên kết chia sẻ" /><button type="button" className={`${cx.btn} ${cx.btnGhost} w-full`} onClick={() => void copy()}>{copied ? "✓ Đã sao chép liên kết" : "Sao chép liên kết"}</button></div>}</div></Modal>;
}
