"use client";

import { useMemo, useState } from "react";
import { gradeFillAnswer, getAcceptedAnswers } from "@/lib/fillAnswer";
import FillFocusSession from "@/components/FillFocusSession";
import LearningQuickDock from "@/components/LearningQuickDock";

type Word = { id: number; meaning: string; term: string | null; example: string | null; wtype: string | null; ipa: string | null; v1: string | null; v2: string | null; v3: string | null };
type Question = { id: number; question: string; answer: string; vnMeaning: string | null; phonetic: string | null; questionType: string; options: string[]; correctOptions: string[]; explanation: string };
export type ShareGuestPayload = { targetType: "vocab_set" | "question_collection"; title: string; count: number; setType?: string; allowedModes: string[]; words?: Word[]; questions?: Question[] };

const labels: Record<string, string> = { learn: "Học bài", fill: "Điền từ", mc: "Trắc nghiệm", match: "Ghép cặp", dictation: "Nghe & viết", pronunciation: "Luyện phát âm", sentence: "Xếp câu", timed: "Thi thử tính giờ", practice: "Luyện câu hỏi", multiple_choice: "Trắc nghiệm", speaking: "Speaking", shuffle: "Xáo trộn câu hỏi" };

export default function ShareGuestExperience({ token, initialMode, payload }: { token: string; initialMode: string; payload: ShareGuestPayload }) {
  const [mode, setMode] = useState(initialMode && payload.allowedModes.includes(initialMode) ? initialMode : "");
  const [index, setIndex] = useState(0);
  const words = payload.words || [];
  const questions = payload.questions || [];
  const modeItems = useMemo(() => payload.allowedModes.filter((item) => labels[item]), [payload.allowedModes]);
  function selectMode(next: string) { setMode(next); setIndex(0); window.history.replaceState(null, "", `/s/${encodeURIComponent(token)}?mode=${encodeURIComponent(next)}`); }
  const activeSession = Boolean(mode);
  return <main className="min-h-screen bg-[#FAF9FD] text-ink"><header className={`border-b border-line bg-white ${activeSession ? "px-4 py-2" : "px-4 py-4"}`}><div className="mx-auto flex max-w-5xl items-center justify-between gap-3"><div className="min-w-0"><div className="text-sm font-extrabold tracking-wide">Lexora</div><h1 className={`max-w-[70vw] font-extrabold ${activeSession ? "truncate text-base" : "text-lg sm:text-2xl"}`}>{payload.title}</h1>{!activeSession && <p className="text-xs text-muted">{payload.count} mục · Được chia sẻ qua Lexora</p>}</div><a className="min-h-10 shrink-0 rounded-lg border border-line px-3 py-2 text-xs font-bold" href={`/login?next=/s/${encodeURIComponent(token)}`}>Đăng nhập</a></div></header><div className={`mx-auto max-w-5xl px-4 ${activeSession ? "py-2" : "py-5 sm:py-8"}`}>{activeSession && <LearningQuickDock availableModes={modeItems} currentMode={mode} onSelect={selectMode} guest />}{!activeSession && <div className="grid gap-3 sm:grid-cols-2">{modeItems.map((item) => <button type="button" key={item} onClick={() => selectMode(item)} className="min-h-14 rounded-xl border border-line bg-white px-4 text-left text-sm font-bold shadow-sm">{labels[item]}</button>)}</div>}{activeSession && payload.targetType === "vocab_set" ? mode === "fill" ? <FillFocusSession set={{ id: 0, name: payload.title, words }} userId={0} sessionKind="practice" retest={false} quickMode={true} mistakeIdByWordId={{}} totalWordCount={words.length} rangeFrom={1} rangeTo={words.length} hasRange={false} onApplyRange={() => undefined} onChooseSet={() => selectMode("learn")} persist={false} chrome="compact" /> : <SharedWordMode mode={mode} words={words} index={index} setIndex={setIndex} /> : activeSession ? <SharedQuestionMode mode={mode} questions={questions} index={index} setIndex={setIndex} /> : <p className="mt-6 text-sm text-muted">Chọn một cách học để bắt đầu.</p>}<p className="mt-8 text-center text-xs text-muted">Bạn có thể học mà không cần tài khoản. <a className="font-bold text-golddark" href={`/login?next=/s/${encodeURIComponent(token)}`}>Đăng nhập để lưu tiến độ</a></p></div></main>;
}

function SharedWordMode({ mode, words, index, setIndex }: { mode: string; words: Word[]; index: number; setIndex: (value: number) => void }) {
  const word = words[index]; const [answer, setAnswer] = useState(""); const [checked, setChecked] = useState(false);
  if (!word) return <Empty />;
  const next = () => { setAnswer(""); setChecked(false); setIndex(Math.min(words.length - 1, index + 1)); };
  if (mode === "match") return <section className="mx-auto mt-5 max-w-2xl rounded-2xl border border-line bg-white p-5"><h2 className="font-serif text-xl font-bold">Ghép cặp tự luyện</h2><p className="mt-2 text-sm text-muted">Lần lượt nhớ nghĩa của từng từ rồi bấm hiện đáp án.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{words.slice(0, 20).map((item) => <button type="button" key={item.id} onClick={(event) => { const target = event.currentTarget; target.textContent = `${item.term || ""} — ${item.meaning}`; }} className="min-h-12 rounded-lg border border-line px-3 text-left text-sm font-bold">{item.term}</button>)}</div></section>;
  const isFill = ["fill", "dictation", "pronunciation", "sentence", "timed"].includes(mode);
  return <section className="mx-auto mt-5 max-w-2xl rounded-2xl border border-line bg-white p-5 shadow-sm sm:p-8"><div className="flex items-center justify-between text-xs font-bold text-muted"><span>{labels[mode] || "Học bài"}</span><span>{index + 1}/{words.length}</span></div><div className="mt-8 text-center"><p className="text-xs font-bold uppercase tracking-wider text-muted">{isFill ? word.meaning : "Từ vựng"}</p><h2 className="mt-3 font-serif text-3xl font-extrabold">{isFill ? "" : word.term}</h2>{!isFill && word.example && <p className="mt-4 text-sm italic text-muted">{word.example}</p>}{isFill && word.example && <p className="mt-4 text-sm italic text-muted">{word.example.replace(new RegExp(word.term || "^$", "gi"), "______")}</p>}</div>{isFill && <input autoFocus className="mt-8 min-h-12 w-full rounded-lg border border-line px-4 text-base outline-none focus:border-gold" autoComplete="off" value={answer} onChange={(event) => setAnswer(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && answer.trim()) { event.preventDefault(); setChecked(true); } }} placeholder="Nhập từ tiếng Anh" />}{checked && <div className={`mt-3 rounded-lg p-3 text-sm ${gradeFillAnswer(answer, word.term).correct ? "bg-okbg text-ok" : "bg-badbg text-bad"}`}>{gradeFillAnswer(answer, word.term).correct ? "Chính xác" : `Đáp án: ${getAcceptedAnswers(word.term).join(" / ")}`}</div>}{!isFill && <div className="mt-8 rounded-xl bg-[#F8F7FF] p-4 text-center"><div className="font-serif text-2xl font-bold">{word.term}</div><div className="mt-2 text-sm text-muted">{word.meaning}</div></div>}<button type="button" disabled={isFill && (!checked || !answer.trim())} onClick={next} className="mt-6 min-h-12 w-full rounded-lg bg-ink text-sm font-bold text-white">{index === words.length - 1 ? "Hoàn thành" : "Tiếp theo →"}</button></section>;
}

function SharedQuestionMode({ mode, questions, index, setIndex }: { mode: string; questions: Question[]; index: number; setIndex: (value: number) => void }) {
  const question = questions[index]; const [answer, setAnswer] = useState(""); const [checked, setChecked] = useState(false); if (!question) return <Empty />;
  const isMc = mode === "multiple_choice" || question.questionType === "multiple_choice"; const correct = isMc ? question.correctOptions.includes(answer) : answer.trim().toLowerCase() === question.answer.trim().toLowerCase();
  return <section className="mx-auto mt-5 max-w-2xl rounded-2xl border border-line bg-white p-5 shadow-sm sm:p-8"><div className="flex items-center justify-between text-xs font-bold text-muted"><span>{labels[mode] || "Luyện câu hỏi"}</span><span>{index + 1}/{questions.length}</span></div><h2 className="mt-8 whitespace-pre-wrap text-lg font-bold">{question.question}</h2>{question.vnMeaning && <p className="mt-3 text-sm text-muted">{question.vnMeaning}</p>}{isMc ? <div className="mt-6 grid gap-2">{question.options.map((option) => <button type="button" key={option} onClick={() => { setAnswer(option); setChecked(true); }} className={`min-h-12 rounded-lg border px-3 text-left text-sm ${checked && option === answer ? correct ? "border-ok bg-okbg" : "border-bad bg-badbg" : "border-line"}`}>{option}</button>)}</div> : <input autoFocus className="mt-6 min-h-12 w-full rounded-lg border border-line px-4 text-base" autoComplete="off" value={answer} onChange={(event) => setAnswer(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && answer.trim() && !event.nativeEvent.isComposing) { event.preventDefault(); setChecked(true); } }} placeholder="Nhập câu trả lời" />}{checked && <p className={`mt-4 rounded-lg p-3 text-sm ${correct ? "bg-okbg text-ok" : "bg-badbg text-bad"}`}>{correct ? "Chính xác" : `Đáp án: ${question.answer}`}</p>}<button type="button" disabled={!checked} onClick={() => { setAnswer(""); setChecked(false); setIndex(Math.min(questions.length - 1, index + 1)); }} className="mt-6 min-h-12 w-full rounded-lg bg-ink text-sm font-bold text-white">{index === questions.length - 1 ? "Hoàn thành" : "Tiếp theo →"}</button></section>;
}

function Empty() { return <section className="mx-auto mt-5 max-w-2xl rounded-xl border border-line bg-white p-6 text-center text-sm text-muted">Nội dung này chưa có dữ liệu để luyện.</section>; }
