"use client";

import { FormEvent, useRef, useState } from "react";

async function safeJson(response: Response) { const text = await response.text(); if (!text) return {} as Record<string, any>; try { return JSON.parse(text) as Record<string, any>; } catch { return {} as Record<string, any>; } }

export default function SharePasswordGate({ identifier, title }: { identifier: string; title: string }) {
  const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submitting = useRef(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (submitting.current || password.length < 6) return; submitting.current = true; setBusy(true); setError(""); try { const response = await fetch(`/api/share/${encodeURIComponent(identifier)}/unlock`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const data = await safeJson(response); if (!response.ok) { setError(data.error || "Không thể kiểm tra mật khẩu."); return; } window.location.reload(); } catch { setError("Không thể kết nối. Vui lòng thử lại."); } finally { submitting.current = false; setBusy(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#FAF9FD] p-4 text-ink"><section className="w-full max-w-md rounded-2xl border border-line bg-white p-6 shadow-sm sm:p-8"><div className="text-center text-lg font-extrabold tracking-wide">Lexora</div><h1 className="mt-5 text-center font-serif text-2xl font-extrabold">{title}</h1><p className="mt-3 text-center text-sm text-muted">Nội dung này được bảo vệ bằng mật khẩu.</p><form className="mt-7" onSubmit={(event) => void submit(event)}><label className="text-xs font-bold uppercase tracking-wide text-muted" htmlFor="share-password">Mật khẩu</label><div className={`mt-2 flex rounded-xl border bg-white ${error ? "border-red-300" : "border-line focus-within:border-[#7865EE]"}`}><input id="share-password" autoFocus className="min-h-12 min-w-0 flex-1 rounded-xl px-4 text-base outline-none" type={visible ? "text" : "password"} value={password} onChange={(event) => { setPassword(event.target.value); setError(""); }} autoComplete="current-password" aria-invalid={Boolean(error)} aria-describedby={error ? "share-password-error" : undefined} /><button type="button" className="min-h-12 min-w-12 rounded-xl text-sm font-bold text-muted" onClick={() => setVisible((current) => !current)} aria-label={visible ? "Ẩn mật khẩu" : "Hiện mật khẩu"}>{visible ? "Ẩn" : "Hiện"}</button></div>{error && <p id="share-password-error" role="alert" className="mt-2 text-sm text-red-700">{error}</p>}<button type="submit" disabled={busy || password.length < 6} className="mt-5 min-h-12 w-full rounded-xl bg-ink px-4 text-sm font-bold text-white disabled:opacity-50">{busy ? "Đang kiểm tra…" : "Truy cập"}</button></form><p className="mt-5 text-center text-xs text-muted">Không cần tài khoản Lexora.</p></section></main>;
}
