"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "next/navigation";
import StudyModeNav from "@/components/StudyModeNav";
import { cx } from "@/components/ui";
import { gradeLanguageAnswer } from "@/lib/languageAnswer";
import { getAvailableModes } from "@/lib/languages";
import { buildSentenceCloze } from "@/lib/sentenceCloze";

type Word={id:number;term?:string|null;alternateTerm?:string|null;pronunciation?:string|null;meaning:string;example?:string|null;examplePronunciation?:string|null;exampleMeaning?:string|null};
type SetDetail={id:number;name:string;type:string;languageCode?:string|null;languageSettings?:unknown;words:Word[]};

export default function ClozePage(){
 const {setId}=useParams<{setId:string}>(); const [set,setSet]=useState<SetDetail|null>(null);const [index,setIndex]=useState(0);const [answer,setAnswer]=useState("");const [checked,setChecked]=useState(false);const [error,setError]=useState(false);const [outcomes,setOutcomes]=useState<Record<number,boolean>>({});const runId=useRef(`${Date.now()}-${Math.random().toString(36).slice(2)}`);
 useEffect(()=>{let active=true;fetch(`/api/sets/${setId}`).then(async response=>{if(!response.ok)throw new Error();return response.json();}).then(data=>active&&setSet(data.set)).catch(()=>active&&setError(true));return()=>{active=false;};},[setId]);
 const eligible=useMemo(()=>set?.languageCode==="zh-CN"?set.words.map(word=>({word,cloze:buildSentenceCloze({word,set})})).filter(item=>item.cloze.eligible):[],[set]);const item=eligible[index];const result=checked&&item?gradeLanguageAnswer({set:set||{},word:item.word,target:"term",userAnswer:answer}):null;
 function submit(){if(!item||!answer.trim()||checked)return;const grade=gradeLanguageAnswer({set:set||{},word:item.word,target:"term",userAnswer:answer});setChecked(true);setOutcomes(current=>({...current,[item.word.id]:grade.correct}));void fetch("/api/learning/mastery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wordId:item.word.id,skill:"orthography_production",result:grade.correct?"correct":grade.nearMiss?"near_miss":"incorrect",sourceMode:"cloze",eventKey:`cloze-${runId.current}-${item.word.id}-${index}`})});}
 function next(){if(index===eligible.length-1&&set){const final={...outcomes,...(item&&result?{[item.word.id]:result.correct}:{})};void fetch("/api/results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({setId:set.id,setName:set.name,mode:"cloze",score:Object.values(final).filter(Boolean).length,total:eligible.length,wrongWordIds:eligible.filter(entry=>final[entry.word.id]===false).map(entry=>entry.word.id),practicedWordIds:eligible.map(entry=>entry.word.id),wordsPracticed:eligible.length})});}setIndex(value=>value+1);setAnswer("");setChecked(false);}
 if(error)return <div className={cx.empty}>Không thể tải bài điền từ trong câu.</div>;if(!set)return <div className={cx.empty}>Đang tải…</div>;if(set.languageCode!=="zh-CN")return <div className={cx.empty}>Chế độ này chỉ dành cho bộ Tiếng Trung.</div>;if(!eligible.length)return <div className={cx.panel}><StudyModeNav setId={set.id} active="cloze" languageCode={set.languageCode}/><div className={cx.empty}>Bộ này chưa có ví dụ chứa đúng một lần từ cần luyện.</div></div>;if(!item||!item.cloze.eligible)return <section className={`${cx.panel} text-center`}><h1 className="text-2xl font-extrabold">Hoàn thành điền từ trong câu</h1><p className="mt-2 text-muted">Đã luyện {eligible.length} câu.</p></section>;
 return <main className="mx-auto max-w-3xl"><StudyModeNav setId={set.id} active="cloze" languageCode={set.languageCode} availableModes={getAvailableModes(set)}/><section className={`${cx.panel} text-center`}><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">Điền từ trong câu · {index+1}/{eligible.length}</p><h1 className="mt-5 font-serif text-2xl font-bold leading-relaxed sm:text-3xl">{item.cloze.prompt}</h1><p className="mt-3 text-muted">Nghĩa từ: <b>{item.word.meaning}</b></p><label className="mx-auto mt-6 block max-w-md text-left text-xs font-bold uppercase tracking-wide text-muted">Nhập chữ Hán<input lang="zh-CN" spellCheck={false} autoCapitalize="off" value={answer} readOnly={checked} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.nativeEvent.isComposing&&!event.repeat){event.preventDefault();submit();}}} className={`${cx.input} mt-2 text-lg`} /></label>{result&&<div className={`mx-auto mt-5 max-w-xl rounded-xl p-4 ${result.correct?"bg-okbg text-ok":"bg-badbg text-bad"}`}><b>{result.correct?"✓ Chính xác":"Chưa đúng chữ Hán"}</b><div className="mt-3 font-serif text-xl text-ink">{item.cloze.fullSentence}</div>{item.cloze.examplePronunciation&&<div className="mt-2 text-golddark">{item.cloze.examplePronunciation}</div>}{item.cloze.exampleMeaning&&<div className="mt-1 text-sm text-muted">{item.cloze.exampleMeaning}</div>}</div>}<div className="mt-6">{!checked?<button className={`${cx.btn} ${cx.btnGold}`} onClick={submit}>Kiểm tra</button>:<button className={`${cx.btn} ${cx.btnGold}`} onClick={next}>{index===eligible.length-1?"Hoàn thành":"Tiếp theo"}</button>}</div></section></main>;
}
