import Link from "next/link";

const skills = [
  { name: "Nghe", score: "7.5", progress: 76, color: "bg-[#7865EE]", icon: "◉" },
  { name: "Đọc", score: "8.0", progress: 82, color: "bg-[#F08B6D]", icon: "▤" },
  { name: "Viết", score: "6.5", progress: 64, color: "bg-[#4CB7A5]", icon: "✎" },
  { name: "Nói", score: "7.0", progress: 70, color: "bg-[#E7B94C]", icon: "◌" },
];

const upcoming = [
  { title: "Ngôn ngữ khi đi du lịch", type: "Nghe · Phần 2", duration: "18 phút", icon: "◉", tint: "#EAE7FF" },
  { title: "Cấu trúc bài luận nêu ý kiến", type: "Viết · Task 2", duration: "24 phút", icon: "✎", tint: "#FFF0E8" },
  { title: "Họ từ trong học thuật", type: "Từ vựng", duration: "12 phút", icon: "Aa", tint: "#E7F7F2" },
];

export default function DashboardPage() {
  return <div className="lexora-page-enter space-y-6">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
      <div><p className="mb-2 text-sm font-semibold text-gold">Thứ Tư, ngày 22 tháng 7 năm 2026</p><h1 className="text-[clamp(1.8rem,4vw,2.55rem)] font-extrabold tracking-[-0.045em]">Chào buổi tối, Santa <span aria-hidden="true">✦</span></h1><p className="mt-2 max-w-xl text-[0.95rem] leading-6 text-muted">Mỗi ngày tiến thêm một chút sẽ tạo nên kết quả lớn. Hãy giữ vững nhịp học của bạn.</p></div>
      <div className="flex items-center gap-2 self-start rounded-full border border-[#E5E1FF] bg-[#F4F1FF] px-3 py-2 text-sm font-bold text-[#6550DB] sm:self-auto"><span className="text-base">✦</span> Chuỗi 12 ngày</div>
    </section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.6fr)]">
      <article className="relative overflow-hidden rounded-[20px] bg-[#302A68] p-6 text-white shadow-[0_12px_30px_rgba(48,42,104,0.18)] sm:p-8"><div className="relative z-10 max-w-lg"><div className="mb-8 flex items-center justify-between"><span className="rounded-full bg-white/12 px-3 py-1.5 text-[0.7rem] font-bold uppercase tracking-[0.14em] text-[#DCD8FF]">Trọng tâm hôm nay</span><span className="text-sm font-semibold text-[#C8C2FF]">01 / 03</span></div><p className="text-sm font-semibold text-[#C8C2FF]">Luyện kỹ năng nghe</p><h2 className="mt-2 text-[clamp(1.5rem,3vw,2.2rem)] font-extrabold tracking-[-0.04em]">Làm quen với các giọng nói</h2><p className="mt-3 max-w-md text-sm leading-6 text-[#D3D0EC]">Luyện tai qua một đoạn hội thoại ngắn về thói quen hằng ngày và kế hoạch du lịch.</p><div className="mt-7 flex items-center gap-4"><div className="h-2 flex-1 rounded-full bg-white/15"><div className="h-full w-[68%] rounded-full bg-[#BDB5FF]" /></div><span className="text-xs font-bold text-[#DCD8FF]">68%</span></div><Link href="/study" className="mt-7 inline-flex items-center gap-2 rounded-[11px] bg-white px-4 py-2.5 text-sm font-bold text-[#302A68] transition hover:-translate-y-0.5 hover:bg-[#F5F3FF]">Tiếp tục bài học <span>→</span></Link></div><div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full border-[28px] border-white/5" /><div className="pointer-events-none absolute -bottom-28 right-16 h-64 w-64 rounded-full border-[22px] border-white/5" /></article>
      <article className="lexora-card flex flex-col justify-between p-6"><div><div className="flex items-center justify-between"><span className="text-sm font-bold">Mục tiêu tổng thể</span><button className="text-muted" aria-label="Tùy chọn mục tiêu">•••</button></div><div className="mt-8 flex items-end gap-2"><strong className="text-5xl font-extrabold tracking-[-0.06em]">7.5</strong><span className="mb-2 text-sm font-semibold text-muted">/ mục tiêu 9.0</span></div><div className="mt-5 h-2.5 rounded-full bg-[#F0EEF7]"><div className="h-full w-[83%] rounded-full bg-gold" /></div><p className="mt-3 text-xs font-semibold text-muted">Bạn đã hoàn thành 83% mục tiêu</p></div><div className="mt-8 flex items-center gap-3 rounded-[13px] bg-[#F8F7FC] p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#EAE7FF] text-sm text-gold">↗</span><div><b className="block text-xs">+0.5 trong tháng này</b><span className="text-[0.68rem] text-muted">Tiếp tục duy trì nhịp học hằng tuần</span></div></div></article>
    </section>

    <section className="lexora-stagger grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{skills.map((skill) => <article key={skill.name} className="lexora-card p-5 transition duration-200 hover:-translate-y-1 hover:shadow-[0_10px_24px_rgba(43,39,74,0.08)]"><div className="flex items-center justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-[11px] bg-[#F3F1FA] text-sm font-bold ${skill.color.replace("bg-", "text-")}`}>{skill.icon}</span><span className="rounded-full bg-[#F6F5F9] px-2 py-1 text-[0.68rem] font-bold text-muted">Band</span></div><p className="mt-5 text-sm font-semibold text-muted">{skill.name}</p><div className="mt-1 flex items-end justify-between"><strong className="text-2xl font-extrabold">{skill.score}</strong><span className="text-xs font-bold text-[#4B9B7E]">+0.2</span></div><div className="mt-4 h-1.5 rounded-full bg-[#F0EEF7]"><div className={`h-full rounded-full ${skill.color}`} style={{ width: `${skill.progress}%` }} /></div></article>)}</section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.65fr)]">
      <article className="lexora-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-extrabold">Hoạt động trong tuần</h2><p className="mt-1 text-xs text-muted">Số phút học trong tuần này</p></div><select className="rounded-[9px] border border-line bg-white px-2.5 py-1.5 text-xs font-semibold text-ink"><option>Tuần này</option><option>Tuần trước</option></select></div><div className="mt-8 flex h-44 items-end justify-between gap-2 sm:gap-4">{[{day:"T2",value:42},{day:"T3",value:65},{day:"T4",value:52},{day:"T5",value:78},{day:"T6",value:48},{day:"T7",value:92},{day:"CN",value:35}].map((item) => <div key={item.day} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className={`w-full max-w-8 rounded-t-[7px] transition-all duration-500 hover:opacity-80 ${item.day === "T7" ? "bg-gold" : "bg-[#E9E6FA]"}`} style={{ height: `${item.value}%` }} /><span className="text-[0.68rem] font-semibold text-muted">{item.day}</span></div>)}</div></article>
      <article className="lexora-card p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-extrabold">Học tiếp theo</h2><p className="mt-1 text-xs text-muted">Danh sách bài học của bạn</p></div><Link href="/study" className="text-xs font-bold text-gold hover:underline">Xem tất cả</Link></div><div className="mt-5 space-y-3">{upcoming.map((item) => <Link href="/study" key={item.title} className="flex items-center gap-3 rounded-[13px] p-2 transition hover:bg-[#F8F7FC]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[11px] text-xs font-extrabold text-[#6550DB]" style={{ backgroundColor: item.tint }}>{item.icon}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{item.title}</b><span className="mt-1 block text-[0.68rem] text-muted">{item.type}</span></span><span className="shrink-0 text-[0.68rem] font-semibold text-muted">{item.duration}</span></Link>)}</div></article>
    </section>
  </div>;
}
